vishanurag/Canvas-Editor

index.html
src/Scripts/Canvas.js

feat: added the capitalise , small , bold and italic buttons to edit the text

---

index.html
src/Scripts/Canvas.js

fixed text disappearing issue

---

index.html
src/.vscode/settings.json
src/Scripts/Canvas.js
src/Styles/Style.css

FIXED ISSUE #17 added shape palette functionalty for enhanced user experience...undo and redo functionality already added

Added shape palette

---

index.html
src/Scripts/Canvas.js

added gsap libraries to animate the website

---

index.html
src/Styles/Style.css

Major Changes made : 
->   Added hover effects for these buttons where their names (Bold, Italic, Uppercase, Lowercase) appear on 
hover.
->  Color Update: Applied distinct colors—green for Save, red for Clear, and blue for Download.

Responsive Design: Improved Button and Text Box Sizes with Custom Hover Effects

---

src/Scripts/Canvas.js
src/Styles/Style.css

Fixes #11 
Here are the changes made.

Background Color gradient

---

index.html

Fixed #38 
Please Check if you liked it.

Done Changes With Homepage Designing

---

src/Scripts/Canvas.js

fixed #32 Error Handling for File Upload
a demo:
https://github.com/user-attachments/assets/c5677951-9eae-48f1-b103-53a9cad24e7e

Error Handling for File Upload

---

edition.html
index.html

#added a new section of draw the text

added a new section of draw text using cursor

---

Contributing.md
README.md

Missing Contributing.md file
This pull request enhances the CONTRIBUTING.md file for the Canvas-Editor by providing clearer guidelines and a more structured format. 
- Closes #66

CONTRIBUTING.md

---

src/Scripts/Canvas.js

@vishanurag  i have optimise canvas rendering using requestAnimationFrame and optimised performance of webpage from 84 to 93 and SEO optimisation as well. i have merge the conflicts thanks for your corporation. please review changes. issue no. is #58 thanks.

optimise canvas rendering

---

index.html

Fixes #3 
made webpage user friendly and added functionality to the buttons 
https://github.com/user-attachments/assets/b91b0ae9-cee4-4ace-ab5c-dbdbfa41bb21

Enhancing web page

---

index.html
src/Scripts/Canvas.js
src/Styles/Style.css

Fixes issue #57 
Added contact us section to the home page below canvas editor
@vishanurag please check this pr and consider merging if no issues

added contact us section the home page

---

index.html

Fixes #74 
I added 3 section , brightness, saturation, blur section
issue#74

added brightness, saturation, blur section also fix the two typo!!#74  

---

index.html
src/Styles/Style.css

Fixes #89 
I have also modifed the exising header and footer along with the palette design 
Please have a look
Screenshots 📸 
@vishanurag Have a look and let me know if any further changes have t be made.
Thank you.

Issue resolved - palette colour

---

about.html

Fixes #82 
About us page successfully added and link to index page closes# 82

Create about.html Closes # 82

---

src/Scripts/Canvas.js

Fixes #33 
ensuring the global fontSize variable is updated correctly in the textSize input event listener before calling the updateCanvas function #33

Font Size Mismatch in Canvas Text Update

---

index.html

Issue No : #93 
https://github.com/user-attachments/assets/962bc899-b8e6-403b-801a-9c67c38dd6ae
I have resolved conflict in previous PR and creatred this new one.
Please Merge the pull request and assigning labels in pull request.
Thankyou!

Added a Custom effect in Cursor

---

index.html
src/Styles/Style.css

- Fixes #99 
- Added Draw section to Nav bar
- Draw section is working

[FIX] Draw section added

---

index.html
src/Styles/Style.css

Fixes #104 
I DID ADD THE FEATURES THAT I COULD AND IT IS FULLY FUNCTIONAL ISSUE NO. #104

BRUSH CLEAR CANVAS  AND ERASER ADDED ISSUE NO. #104

---

index.html
src/Styles/Style.css

This PR resolves [#35 ] by improving the alignment and spacing between the canvas area and the control panel. The layout now has consistent spacing, and the elements are better aligned for a more visually appealing interface.
Fixes #35  
- Adjusted the CSS for the canvas and control panel.
- Improved the padding and margin to ensure consistent spacing.
**Before:**
**After:**

Fix: Alignment and Spacing for Canvas and Control Panel

---

index.html

removed the horizontal scroll

---

index.html
src/Styles/Style.css
src/Styles/contact_us_style.css

Fixes #131
I have make changes on contact us form and it's styling by adding a new css file and also make changes in index.html file. Now the contact us section is visually appealing. This is #131 issue which i resolved.  You can check the screen shot below 
kindly assign labels gssoc-ext, hacktoberfest-accepted level2 while merging

contact_us section visually appealing

---

index.html

Fixes #37 
I have implemented a drag-and-drop feature in this project. Users can hold an item to drag it to a canvas section of the page, where the image will automatically be uploaded. Once on the canvas, users can edit the image.

 Drag-and-Drop Feature #37

---

Contributing.md
README.md

This is with reference to issue #98 . I have made the changes as proposed in my PR. Please review it and let me know if any changes are required.

Update: Contributing.md

---

index.html
src/Styles/Style.css

button problem #165 
now buttons are not shaking
https://github.com/user-attachments/assets/f8fdb925-23af-4e45-8918-9f499fc46b17

now buttons are not shaking

---

about.html
index.html
login.html
signup.html

The Login Page and Sign Up page for the webpage have been completely done.
Some other changes have also be done as it shows error in the about.html and index.html like missing of brackets.
The Login page username , password and continue with google option.
The sign up page has name, mail id, confirm password and continue with google .
@vishanurag The issue number is #112 
Can you assign level 3 as i worked on creating two sections for the project.
Uploading video canvas.mp4…

Features: Sign Up and Login Page #112

---

index.html

https://github.com/user-attachments/assets/1d85d6c6-bf17-421f-a31c-62aeb8200ac7
#156 
• Fixed the bug which created an uncanny distance between the actual cursor and the actual drawn point on canvas.
• Also, removed the redundant lower Canvas that actually didn't work.
• Also, removed the Navbar in the middle of the page.
@vishanurag Please let me know if it is alright. Also, please add the GSSoC Extended and Hacktoverfest labels on this. Thank you so much!!

Fixed the bug #156

---

about-us.html
index.html

Fixed wrong link path and Image path.
Issue #207
Kindly check and merge asap @vishanurag

[BUGFIX] Fixed broken links and image path

---

.github/workflows/greetings.yml

Fixed #191 
**Description:**
I  implemented a new GitHub Actions workflow named "Greetings," which automatically greets users who open new issues or pull requests in this repository.
**Key Features:**
- **Automatic Greeting**: Users will receive an immediate acknowledgment when they create an issue or pull request. The messages are:
- **For Issues**: "👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our team will review it shortly. Stay tuned!"
- **For Pull Requests**: "🎉 Thank you for your contribution! Your pull request has been submitted successfully. A maintainer will review it as soon as possible. We appreciate your support in making this project better."

Feature: Implement GitHub Workflow for Automated Greetings

---

index.html

Updated Social links #201

---

.github/Issue_templates/BUG_report_issue_template.md
.github/Issue_templates/Feature_request_issue_template.md
.github/Pull_Request_template.md

✅ Fixes #144 
This PR includes changes to add new & improved Issue templates & PR template that can be used by new contributors to easily create informative issues & PRs that contain precise info.
* [`.github/Issue_templates/BUG_report_issue_template.md`](diffhunk://#diff-cd1511db3bf5a562cd0cf61f23d23c23fede8b616a4355f838f162db1aff382fR1-R52): Added a comprehensive bug report template to guide users in reporting issues effectively.
* [`.github/Issue_templates/Feature_request_issue_template.md`](diffhunk://#diff-5c16b96d83a8e5707e875b870541ec55a83ddaf6cd57000b70b8f32dbbcdfa0bR1-R52): Introduced a detailed feature request template to streamline enhancement proposals.
* [`.github/Pull_Request_template.md`](diffhunk://#diff-c710f5ed7890dd18e8c61a036ace3fd59ebf932352fde36aac92b35d70e7cb09R1-R58 …

Add Issues & PR templates

---

login.html

Added email validation

---

about-us.html
index.html
src/Styles/Style.css

**before**
https://github.com/user-attachments/assets/e959c3d0-1cf4-4b6f-ab22-d17de54c00c7
**after**
https://github.com/user-attachments/assets/bd47b944-884a-4f96-ba08-961ebb05d21e
** Issue #223 **

To adding animation effect to social media icons

---

about-us.html

fix: Update footer links to ensure proper redirection
Related Issue
Closes: #204 
Description
In this pull request, I have resolved the issue with the footer links not directing users to the intended URLs. A hyperlink has been added to the footer for the name "ANURAG VISHWAKARMA," linking to the specified GitHub profile. This change enhances user accessibility to important social media and professional pages.
How Has This Been Tested? ⚙️
I tested the links in the footer by clicking on them and verifying that they redirect correctly to the specified URLs without any errors. The link to the GitHub profile opens in a new tab as expected.
Screenshots 📷
Type of change
Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which …

changes made on footer part

---

index.html

This solves issue #204 
I have added hyperlink "ANURAG VISHWAKARMA " to their GitHub profile, in the footer section.
Please assign this with the corresponding labels and levels @vishanurag

Added hyperlink to Anurag's Github profile

---

index.html

Hey @vishanurag ,
Issue closes #311 
I have styled the vertical scrollbar to a scrollbar with transition colors adding more effectiveness of the website.

Styled the Vertical Scrollbar.

---

README.md

✅ Closes: #220
Closes: #220 
This pull request includes several enhancements to the `README.md` file to improve its visual appeal and organization. The most important changes include adding a table to display project statistics, enhancing the contributor acknowledgment section, and making minor formatting adjustments.
Visual and organizational improvements:
* Added a table to display project statistics such as stars, forks, issues, open PRs, closed PRs, languages, and contributors. (`README.md`)
* Enhanced the contributor acknowledgment section with additional text and removed the old contributors image. (`README.md`)
Minor formatting adjustments:
* Replaced plain text with HTML tags for better alignment and styling. (`README.md`)
* Changed the introductory text to bold for better …

docs:  Add social Badges & fixed some padding & align on header

---

about.html
index.html
login.html
signup.html
src/Scripts/preloader.js
src/Styles/Style.css

Closes: #230 <issue number>
Styling has been applied to the preloader and scroll bar. The preloader is present on all pages of the website with styling. The scroll bar behavior has been improved and the thumb and track have been redesigned, resulting in improved scroll behavior.
*Improvements:*
1. *Optimized Preloader:* Enhanced the preloader animation on the About Us, Index, Login, and Sign Up pages to improve user experience.
2. *Revamped Preloader Design:* Redesigned the preloader with modern CSS styling to enhance visual appeal.
3. *Dedicated Preloader Script:* Created a separate JavaScript file named "preloader.js" to manage the preloader functionality, ensuring better code organization and maintainability.
The program was tested locally on a machine using the Chrome browser. To …

feat:  Improve Scroll Bar and Preloader

---

login.html
signup.html
src/Styles/signup.css

Successfully updated SignUp and Login Page
Closes: #202 
So, I have changed the UI of signup and login page to make it look more appealing, as the website is related to canvas editing, so I thought of some cool background it make it look rich!

Updated SignUp and Login Page

---

index.html
src/Styles/Style.css

closes #182 
added back to top button for better navigation

Added back to top button

---

src/Styles/Style.css

Closes: #301 
hello PA
i have added the underline hover effect  properly 
Uploading Screen Recording 2024-10-09 123506.mp4…

adding underline hover

---

signup.html

Closes: #325 
I have added a responsive password strength level meter to the signup page. 
I have tested the password meter by inputing different types of passwords.

feat: Added password meter

---

blog.html
review.html

#347
fix title name in blog.html and review.html
blog.html and review.html title name tested
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I have ensured my changes don't generate any new warnings or errors.
- [x ] I have updated the documentation (if necessary).
- [x ] I have resolved all merge conflicts.

fix title name in blog.html and review.html

---

Blog_page.html
Faq.html
about-us.html
blog.html
contributors.html
edition.html
index.html
login.html
review.html
signup.html
welcome.html

#360 
https://github.com/user-attachments/assets/f508f940-edda-447f-8389-cfa6b6ed8389

Added a Custom Cursor effect

---

index.html
src/Styles/Style.css
src/Styles/contact_us_style.css

Fixed the CONTACT US overflowing contents
(BEFORE)
(AFTER)
ALSO changed the CANVAS BOX SIZE equal to the elements size
(BEFORE)
(AFTER)

Fixed the CONTACT US overflowing contents also changed the UI of canvas

---

signup.html

ISSUE NO. #411 
- [X ] Have you renamed the PR Title in a meaningful way?
Closes: #411 
The function now displays a message after validating password confirmation.
Testing Methodology
1. Form Completion
2. Password Validation Check:
3. Success Message Verification
4. User Experience Review
The changes have been thoroughly tested, and we verified that the success message displays correctly upon form submission without affecting other form functionalities. This implementation effectively guides the user toward the next action (login) upon successful account creation.
- [ X] New feature (non-breaking change which adds functionality)
- [ X] Code style update (formatting, local variables)
- [X ] My code follows the code style of this project.
- [ X] I have …

Confirmation Upon register

---

.vscode/settings.json
index.html

Text size changed and it is now visible.
Issue Resolved: #414
Closes: #<issue number> #414
I have changed the text size to make it more visible in the website.
- [x ] I have ensured my changes don't generate any new warnings or errors.

Text size changed

---

index.html

aligned submit button to center
@vishanurag please review and merge it

Fixed #416 - aligned submit button to center 

---

signup.html

Fixes #460
added back to home in sign in page

Added Back to home button in Sign up page #460

---

index.html
signup.html

Fixes #458
Added darkmode in Homepage 
@vishanurag please review and merge it

Added Darkmode in Homepage #458

---

README.md
about-us.html
index.html
testimonial.html

Have Revamped "Review" Page and renamed it to "Testimonial". Added lot of images, effects, stylings to make it attractive!
Fixes #384
https://github.com/user-attachments/assets/e8691b80-09e8-46de-ac3b-5bc076ec4039

Testimonial page revamp

---

login.html
signup.html

Have 
- Inserted App logo in login and sign up page
- Improved back to home button and its responsive ness
- removed showing 'login' in login page and same case for signup page.
This fixes #479 
Screenshots:

signup and login page fixes

---

index.html

Closes: #436 
This PR adds a "Clear Canvas" button that allows users to clear all content on the canvas, providing an easy way to reset the drawing area.
- Manually tested the button functionality to ensure it correctly resets the canvas without affecting other features.
- Tested across multiple devices and browsers for consistency.
https://github.com/user-attachments/assets/de015025-210c-4f2b-8c53-6669ec275e89

added clear canvas button functionality (working)

---

login.html

Closes: #419 i.e Blank Space Problem in login page.

Blank space Problem Solved

---

login.html
signup.html

This PR closes issue #393
##Description
In the signup page and the login page, there was a lock icon in the password fields. I replaced it with eye icon and also added functionality for the eye icon such that we can toggle the eye icon to change between "visible password" and "hided password".
##Output screenshots
Note: Some of the changes in this PR are from pulling the latest updates from the upstream repository to sync my branch.
@vishanurag Kindly review at the earliest

Added eye icon for password field to toggle

---

Blog_page.html
README.md
about-us.html
index.html
privacy.html
review.html

Closes: #318 
I have synced the logos on all pages to make it look neat and uniform. I have also added changes to the footer and added responsiveness to the icons. While working I faced conflicts and then 2 new pages were added later to that. I have also modified the **GSSoC Extended 2024** and **Hacktoberfest 2024** acceptance banners to your README.md file so that Contributors can find it easily and know that this repository is participating in these programs.
I have checked the redirects of all the icons multiple times and added your social(LinkedIn) as requested before.
- Home Page
- About Us page
- Review Page
- Privacy Page
- Blog_page
- GSSoC Extended 2024 & Hacktoberfest 2024 acceptance banners

Updated Footer Icons, Reponsiveness on the Icons & Modified Program banners in README file

---

Faq.html

- [x ] Have you renamed the PR Title in a meaningful way?
Closes: #368 
I have added the header and Footer to the FAQ page
before:
After changes:
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this project.
- [x ] I have followed the contribution guidelines
- [x ] I have ensured my changes don't generate any new warnings or errors.
- [x ] I have resolved all merge conflicts.

FAQ page header and Footer(issue #368)

---

index.html

fix: ( color of topmost heading on homepage after toggle )
Fixes: #539
This pull request resolves the issue where the topmost heading does not update properly after toggling the visibility of content  sections. The changes ensure that the heading accurately reflects the current state of the toggled sections.
1. Click on toggle button.
2.  Dark mode is applied.
3.  The color of topmost heading on homepage will automatically change.

fixed color of topmost heading on homepage after toggle

---

Blog_page.html
Faq.html
testimonial.html

Closes: #492 
1) FAQ enhanced, home page navigation added.
2) navbar with navigation to all other pages added in testimonial page.
3) blog page navbar links are now working.
By running on my system with live server.
1) Before FAQ can be seen in the issue.
After version:
2) Navigation to all other pages added in the testimonial page for easy user navigation and better user experience.
3) Blog_page links are now working, you can now navigate to home page when you click on it, navigate to design section with smooth scroll behaviour, Go to create blog page.

faq enhanced and navbar navigations on different pages

---

index.html

#601 
Closes: #601 
Originally the background color of div.row.text.center.p-5 was blue , I have changed it to Deep Navy blue.
I have tested it by opening the updated code in chrome browser.

Updated row.text.center.p-5 background color

---

Blog_page.html

Closes: #603 
Running locally on my system.

Blog page placeholder text update

---

index.html
src/Styles/Style.css

Message Us section 
Closes: #595 
I've changed the complete interface of the your message section.
User interface enhancement
-->

Changed the UI of the your message section

---

Blog_page.html
Faq.html
about-us.html
about.html
blog.html
community.html
contributors.html
edition.html
index.html
login.html
privacy.html
review.html
signup.html
src/Styles/Style.css
src/Styles/scroll.css
testimonial.html
welcome.html

I customized the scroll bar by making it wider, with a white background track and a violet draggable thumb that becomes blue when hovered over. I also rounded the thumb for a smoother look. #586 
https://github.com/user-attachments/assets/e60e9e84-2993-4f54-b118-79bf8556937f
@vishanurag Please merge this

Added scroll bar 

---

index.html

Closes: #616
I have added Multi-Language Support Using Language Translator API that will helps to convert the website text to the multiple country languages.
https://github.com/user-attachments/assets/ccb82687-7cc4-458c-8a72-60c6d5b552b8

Multi-Language Support Using Language Translator

---

Blog_page.html

hey @vishanurag 
I have added the scroll reveal effect and also improved the overall aesthetics of the blog template/page, i have attached a demo video for your reference , kindly check
https://github.com/user-attachments/assets/55d3ea54-3f18-458f-a8a5-962ca4bca239
add the labels : gssoc extd , hacktoberfest 
If you like my work please add level 3 label

improved blog page,scroll reveal 

---

Contributing.md

`<621>` 
Closes: #621 
Changes I have made :-
1) Added a project structure section
2) Added alternate method of contribution through GitHub desktop section
3) Added issue report process section
4) Added a help section
5) Added good coding practices section
I have tested by preview and ensured that all alignments and structures were correct. I have check each line also for any changes if required.

docs: Enhanced And Added New Sections In Contributing.md

---

index.html

Fixes #617
The CSS for the welcome header has been updated to improve the clarity of the glowing purple gradient effect. The text shadow values were refined to reduce blurriness, resulting in a sharper appearance. A linear gradient background in light purple shades was applied for the light theme, enhancing visual appeal. The dark theme retains a glowing white effect for the header to maintain readability against the dark background. These adjustments ensure a vibrant and clear presentation in both themes.

Made the necessary UI enhancements along with alignment correction in some part

---

index.html
src/Styles/contact_us_style.css

style: Contact Us page alignment its input field and button
style: Message box alignment has been been correctly
Closes: #635 
I have corrected the styling of the whole Contact Us page as well as message box page as well.

Contact Us page proper alignment and message box alignment

---

README.md

Closes: #659 
It will help to improve the readme.md file and also helpful for viewers to find the information quickly.
As I added the real images of this website("Creative Canvas Tool").
I've added these 5 images.

Added screenshots | Fixes #659

---

login.html
signup.html

Closes: #604 
Placeholder text more clearly visible, username and email placeholder correctly positioned
By running on live server
Before 
After
Before
After

signup login enhance

---

README.md

Closes: #665 
removed depreciated hacktober fest logo and added a new one
tested the readme locally  

docs:  removed depreciated hacktober fest logo and added a new one (fixed #665)

---

index.html
src/Scripts/Save.js

Added the save as image button functionality that saves your current canvas work as a png .
Fixes #69

Implemented Save as Image funtionality of the canvas work

---

index.html

Closes: #681 
yes I have tested and compared with the current website
Before
After
I have fixed the orientation also I have make the line (Welcome to the Canvas Editor!) as color changing.
- [x ] I have updated the documentation (if necessary).

fixed proper orientation

---

src/Styles/Style.css

change in css , changed font size for better visibility in style.css

---

about-us.html

Closes: #717 
I have improved the orientation of about us section.
I have tested by running the file.
Before
After

FIX:ORIENTATION OF ABOUT US

---

src/Styles/contact_us_style.css

before  i solved the issue the contact us option is not visible but it is correct now
issue #694 
After

Contact us visibility problem solved

---

Blog_page.html
index.html

Issue no. #313
hey @vishanurag sir,
so sorry for this late sir.
I've modified the the canvas palette, kindly review once.
Changes few bugs also,
Before:
https://github.com/user-attachments/assets/b5de2d96-e315-426c-82d6-f677080fac8f
After:
https://github.com/user-attachments/assets/4127434b-c4b6-4afc-a986-bc2bc4858ed9
Changes done:
1.fixed the alignment of the entire home page
2.modified canvas palette
3.adjusted few alignments
Please let me know if any further adjustments are needed.

Color palette improved.

---

about-us.html
index.html
testimonial.html
tutorial.html

Closes: #727 
Have added tutorials page for canvas editor webpage to make it more powerful for those who struggle to use the tool
https://github.com/user-attachments/assets/437f6e7f-6719-4361-a941-de818677154b

Add Tutorials page

---

login.html
signup.html
src/Styles/signup.css

Closes: #639 
I fixed the layout of the page, improved hovering effects
I ran my code several times to check everything is good or not
https://github.com/user-attachments/assets/77ca1c3f-7718-48cb-bf6d-4b11aea7a9ce

Sign up and login pages fixed and enhanced 

---

Faq.html

Closes: #678 
1) Additional home button in front of canvas title removed
2) while opening faq question, an unwanted scroll-bar can be seen which is disturbing the user effect -> it was changed.
By running on live server
Before:
https://github.com/user-attachments/assets/2e559a83-96b2-42d5-b3b2-00553290facc
After:
https://github.com/user-attachments/assets/1a33d18e-472f-482b-9e11-48139afbb27b

FAQ enhanced -additional home button removal and scroll effect update

---

review.html

Closes: #749 
Added styles to the navbar of the reviews page and make it look consistent with the other pages

feat: Added navbar styles to the review page

---

login.html
signup.html

Closes #750
I have changed the color of input fields of signup page to white so that they are more readable now....(also i modified the color of placeholders, so it is more readable)
I have adjusted the alignment of signup and login button in both login and signup pages.
Note: (I have fixed this for mobile version because the text is already readable in desktop version)
Before:
After:
@vishanurag @somyadipghosh Kindly review the PR at the earliest

Fixed the signup page input fields text to be more visible

---

.github/scripts/update_structure.py
.github/workflows/update-readme.yml
README.md
repo_structure.txt

Closes: #762 
Automated project structure updation using github workflows, python scripts and action bot
Tested locally

feat: Automated project structure updation using github workflows, python scripts and action bot

---

index.html

@somyadipghosh @vishanurag please review and merge

Fixed duplicate element from Footer in homepage

---

index.html

@somyadipghosh Please review and merge it in higher level
before
after

Fixed homepage 

---

blog.html
community.html

**fix**: Updated Twitter X (in blog), container alignment & border radius of cards (in community)
1. **Updated Twitter Icon:** Changed the Twitter bird icon to the new **"X" logo** in `blog.html` for valid representation.
2. **Community Section Improvements:**
- **Aligned** the `.container` div under the community-section for improved layout and structure.
- Added **`border-radius`** to the `.card` div to give the cards a smoother, rounded appearance.
These enhancements improve the overall user experience and align with current branding standards.
I kindly request that this pull request be labeled with **Hacktoberfest** and **GSSoC** extn for tracking purposes. Thank you for considering my requests!
**Fixes #757**

fix: Updated Twitter X (in blog), container alignment & border radius of cards (in community).

---

repreviewfix.html

Fixes #686 
I will also add the screenshots and recording

fixed review for some devices

---

about-us.html
index.html

@somyadipghosh please review and merge it in higher level
before
after

Fixed About us Footer 

---

index.html

@somyadipghosh please review and merge it

Fixed Your Message in homepage

---

Blog_page.html
src/Styles/Style_Blog_page.css

Closes: #751
I have removed the duplicate set of cards in the blogs page.
Also the headings in the blog page where not visible because of their color and background color being the same..resolved that also... Also I aligned it properly
##Output Screenshots 📷
@somyadipghosh @vishanurag Kindly review the PR at the earliest..

Removed duplicate cards in blogs page and also made the heading visible

---

Faq.html
about.html
index.html

Hello, PR
Add Translation tool - #778 
Done -
https://github.com/user-attachments/assets/2ab264ed-c7ec-46ae-8ed9-90c75ea2fc37

Add a Translation Tool done ! #778

---

index.html
src/Contributor.css
src/Contributor.html
src/Contributor.js

Hello, PR
Add new feature - #777 
Add Contributors page done -
https://github.com/user-attachments/assets/f20e18ad-97ce-4d6a-b27b-caa8e9459fd4
Page link -

Add a new contributors page done ! #777

---

index.html
visi.css
visi.js

Hello, PR
Add new feature - #852
Add Visitor Counter feature done properly -
Before -

✨Add Visitor Counter feature done ! #852

---

about-us.html

Examples of good PR titles:
build:      (for build related changes)
chore:      (for updating task runner configs etc; no production code change)
docs:       (for documentation changes)
feat:       (for new feature)
fix:        (for bug fixes)
perf:       (for performance improvements)
refactor:   (for refactoring code; no production code change)
revert:     (when reverting changes)
style:      (changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc))
test:       (when adding missing tests)
-->
Closes: #749 
I had ran the code several times to check if there's any issue
https://github.com/user-attachments/assets/9e0fcbc0-9b27-4856-99b6-8d778f23b1cf
I have redesigned the entire about us page.
-->

About us Re-designed

---

Faq.html

Closes: #823
The FAQ page did not have scroll bar in the mobile version which blocked the user to see a part of the webpage..
I have fixed this and  enabled the scrollbar for the mobile version...
@somyadipghosh @vishanurag Kindly review the PR

Added scrollbar for mobile version of FAQ page

---

src/Styles/Style.css

Changed the Square to rounded button with pastel theme UI
Issue #703 
As I have seen the home page is made with light purple and blue theme so I decided to change the dark buttons to pastel colour so it looks good altogether
I have tested in local host

Style: Button UI

---

index.html

Closes: #833 
Solved Jumbling which was occuring earlier.
**Before**
**After**
https://github.com/user-attachments/assets/5035bd90-0659-43b6-babe-54b67cbfc486

(Fix)Navigation Bar Visual Issues - Spacing and Alignment has been Fixed.

---

blog.html
index.html

#791 Solved
I added Dark mode Toogle that enhance or add the dark mode theme in the home page.
https://github.com/user-attachments/assets/3da50387-ef3d-4671-a3bb-a5d72db53845

Add Dark theme at home page

---

blog.html
index.html

#800 Solved
Update the Blog Page 
https://github.com/user-attachments/assets/41fdba3a-5651-4419-ad2c-1d776ac327a0

Update the Blog Page

---

src/Styles/Style.css
src/Styles/contact_us_style.css

Examples of good PR titles:
build:      (for build related changes)
chore:      (for updating task runner configs etc; no production code change)
docs:       (for documentation changes)
feat:       (for new feature)
fix:        (for bug fixes)
perf:       (for performance improvements)
refactor:   (for refactoring code; no production code change)
revert:     (when reverting changes)
style:      (changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc))
test:       (when adding missing tests)
-->
Closes: #820 
I changed the design of the form
I have checked the code several times to make sure it generates no new warnings
Design

Contact us form enhanced

---

src/Styles/contributor.css

Closes #828 
In the mobile version, I have fixed the alignment of contributor cards.
Before: (mobile screenshot)
After:
@vishanurag @somyadipghosh Kindly review the PR at the earliest

Fixed contributors alignment on mobile version

---

testimonial.html

Closes: #902 
There was a Duplicate navbar on the Testimonial page and some CSS code was there.
Go to the Testimonial page and see there is no duplicate navbar and CSS style line.

FIX : Duplicate navbar on Testimonial page

---

about-us.html

fixes #889 
Updated the UI of the about page
Before change :
After change:

Updating the about page

---

README.md
repo_structure.txt
signup.html

Closes: #892 
Updated the code perfectly, so that the duplication of lines or paragraphs do not happens again.
- Before
- After

Duplicate "Already have an account?" text on the login page 

---

README.md
login.html
repo_structure.txt

Examples of good PR titles:
Closes: #900 
There was a duplicate navbar on the Login page.
Go to the login page and see there is no duplicate navbar.
Before 
After

FIX : Duplicate navbar on Log in page

---

index.html
src/Styles/Style.css

fixes #772 
This PR fixes the alignment issues in button and also redesinged the size,colour of buttons to make it more visually more appealing.
Before:
After:
https://github.com/user-attachments/assets/21b1781c-21b8-4480-8e44-7419a19a5784

Realigning and redesigning of buttons

---

index.html

Fixes #753
###Canvas tools are working now!!
Background color, brush color, brush size and background-image are getting changed on selecting from the inputs. Please check. 
Thanks

fix: Made the tools buttons working 

---

README.md

`docs: Update troubleshooting guide and configuration issues`
Closes: #816
This pull request updates the troubleshooting section of the documentation to include common issues encountered during installation and wallet connection, along with their solutions. It also outlines best practices for configuring the development environment and tips for optimizing performance during smart contract deployment. 
The changes have been reviewed for clarity and accuracy. No code changes were made, so testing was not applicable. The troubleshooting solutions were verified against common issues experienced during development.
Not applicable since my work was changing the documentation.

updated readme with troubleshooting section

---

src/Styles/Style.css

- [x ] Have you renamed the PR Title in a meaningful way?
Closes: #811 
previosly contact us text was not visible to due bad color changed the color code to #f9f9f9(white) to make it visible 
**before
**
**after
**
changed the color code of contact us text to make it more visible which was not possible earlier
- [ x] Bug fix (non-breaking change which fixes an issue)

making contact us text visible

---

index.html

Added Font style,Font Family and Font Weight Dropmenu and added animations and transitions to that.

Added different font styles,font weights and font family

---

review.html

Review can show

---

README.md
index.html
repo_structure.txt

@somyadipghosh and @vishanurag please review and merge it
before
after

Fixed whole home page

---

README.md
about-us.html
index.html
repo_structure.txt

@somyadipghosh please review and merge 
before
after

Fixed about us page navbar

---

README.md
about-us.html
index.html
privacy.html
repo_structure.txt

@somyadipghosh @vishanurag please review and merge in higher level
before
after

Updated the footer of Privacy Page

---

Blog_page.html
README.md
about-us.html
index.html
privacy.html
repo_structure.txt

upgraded whole blog page , please make it higher level
@somyadipghosh @vishanurag please review and merge it
before
after

Upgraded Whole Blog page

---

review.html

fixes #944
Before:
After enhancement:

Shamvrueth

---

index.html

https://github.com/user-attachments/assets/e24a03cf-9015-4331-8523-9c1d94984ab9

Fixed and Enabled Progress Bar and Chatbot .

---

index.html

https://github.com/user-attachments/assets/40214c5c-a0d3-4569-a4cc-7107d98d7941

Added Top-to-bottom Scroll button 

---

index.html

Syntax errors Solved

---

src/Styles/contact_us_style.css

Fixes #950
- [ x] Have you renamed the PR Title in a meaningful way?
- [x ] My code follows the code style of this project.

now submit button is in center

---

index.html
src/Styles/contact_us_style.css

Closes: #949 
i have given the required space between your and message
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] Code style update (formatting, local variables)

given the required space

---

index.html
src/Styles/contact_us_style.css

Closes: #948 
i have placed message box in center
- [ x] Bug fix (non-breaking change which fixes an issue)

placed the message box in center

---

index.html
src/Styles/contact_us_style.css

Closes: #947 
i have changed the color and now the word is clearly visible
- [x ] Bug fix (non-breaking change which fixes an issue)

changed the color

---

index.html
package-lock.json
package.json

[Fix] : Code Display Fixed
Closes: #907 
the code of script is shown in the deployment now that is fixed in this pull request
Before 
After
The function was copied and pasted and the script tag was not closed which caused this issue. It was resolved in this pull request

Code display fix

---

README.md
index.html
repo_structure.txt

@vishanurag @somyadipghosh please review and merge it 
before
after

Fixed whole homepage 

---

about-us.html

@vishanurag @somyadipghosh please review and merge it
before
after

Upgraded whole About us page

---

privacy.html

@vishanurag @somyadipghosh please merge it in higher level
after
https://github.com/user-attachments/assets/64414143-7da9-400c-a442-7f4aaf28e2a4

Upgraded whole Privacy Page

---

index.html

1. Made the toggle button functional
2.Enhanced navbar

Made toggle button functional and enhanced navbar

---

about-us.html

Title of the Pull Request
[✔] Have you renamed the PR Title in a meaningful way?
Description
In the about us page the UI was not good and also there was no nav bar therefore added the nav bar and enhanced the CSS of that page
Type of change
[✔] Bug fix (non-breaking change which fixes an issue)
[✔] New feature (non-breaking change which adds functionality)
[✘] Code style update (formatting, local variables)
[✘] Breaking change (fix or feature that would cause existing functionality to not work as expected)
[✘] This change requires a documentation update
Checklist
[✔] My code follows the code style of this project.
[✔] I have followed the contribution guidelines
[✔] I have performed a self-review of my own code.
[✔] I have ensured my changes don't …

Changed the about us page to enhance UI and also added nav bar

---

index.html
visitor.css
visitor.js

Hello, PR
Add new feature - #985
Add Visitor Counter feature done properly - 
before - 

✨Add Visitor Counter feature done ! #985

---

Blog_page.html

Closes: #953 
Tested by running in live preview.
Before:
can be seen in issue
After:

blog page proper text alignment

---

index.html

- [
] Bug fix (non-breaking change which fixes an issue)
before changes
https://github.com/user-attachments/assets/e6fcebce-444f-4a52-a2d8-b7482e244a07
https://github.com/user-attachments/assets/f81489d8-b87d-4599-b6e4-f44791212ca0
after changes
https://github.com/user-attachments/assets/887cbf23-51f1-4557-a284-8278e869a904

#999 Address Multiple Instances of Text Repetition to Enhance Design Professionalism

---

.github/ISSUE_TEMPLATE/bug.yml

Closes: #1022 
This pull request enhances the Contributor Section by improving the visual layout and organization, making it more user-friendly and informative. Additionally, it includes minor formatting and style improvements to keep the overall README consistent.
This update was tested by:
- Reviewing the appearance of the Contributor Section on a local preview of the README.
- Ensuring compatibility across various screen sizes.
- Checking for any rendering or formatting issues in Markdown.

CREATE BUG REPORT TEMPLATE

---

.github/ISSUE_TEMPLATE/enhancement.yml

Closes: #1028 
I add the enhacement template

Create enhancement template

---

.github/ISSUE_TEMPLATE/documentation.yml

Closes: #1024
This pull request enhances the documentation to improve clarity and usability for new and existing contributors. Key changes include:
- Reorganized `ISSUE_TEMPLATE` for better flow
- Updated installation and setup instructions
- Added a FAQ section to address common issues
- Improved formatting and readability across pages
Documentation changes were reviewed for clarity and tested by setting up a clean environment using the updated instructions. Feedback was also collected from new users to confirm improvements.

CREATE DOCUMENTATION UPDATE TEMPLATE

---

login.html

The navbar and login box container in login page are not properly aligned so, I improved the login page design
Closes: #996 
This pull request enhances the user interface (UI) of the login page and the navigation bar to provide a more modern and user-friendly experience.
1. Navbar Improvements:
-> Updated the navbar background color to a more visually appealing combination of black and white.
-> Increased spacing between navbar items for a cleaner layout.
2. Login Page Enhancements:
-> Enlarged the input fields for the email and password, making them easier to interact with.
-> Created a typing effect for the heading "Design and create stunning visuals effortlessly!" to enhance visual appeal.
-> Added space between the social media icons for better separation.
Navigate to the login page …

I Improved the UI of login page

---

index.html
package-lock.json

Closes: #988
https://github.com/user-attachments/assets/ba9c9446-ad20-460e-a84b-04b4ff3fd021

MADE THE CHANGES

---

signup.html

Title of the Pull Request
[✔] Have you renamed the PR Title in a meaningful way?
Description
The sign up page was not looking good so enhanced its UI to increase user experience.
Type of change
[✔] Bug fix (non-breaking change which fixes an issue)
[✔] New feature (non-breaking change which adds functionality)
[✘] Code style update (formatting, local variables)
[✘] Breaking change (fix or feature that would cause existing functionality to not work as expected)
[✘] This change requires a documentation update
Checklist
[✔] My code follows the code style of this project.
[✔] I have followed the contribution guidelines
[✔] I have performed a self-review of my own code.
[✔] I have ensured my changes don't generate any new warnings or errors.
[✘] I have …

Changed the sign up page to enhance the UI / UX 

---

.github/workflows/issue-reminder.yml

**created issue reminder workflow**
- [ x] Have you renamed the PR Title in a meaningful way?
Closes: #1033 
fixed #1033 
Description: Create a GitHub Actions workflow that sends reminders on open issues without updates for 7 days. The workflow should post a comment prompting assignees to take action.
- [ x] New feature (non-breaking change which adds functionality)
- [x ] My code follows the code style of this project.

created issue reminder workflow

---

review.html

Title of the Pull Request
[✔] Have you renamed the PR Title in a meaningful way?
Description
The UI of the review page is not good,  Updated the overall design to be more visually appealing so as to enhance user experience.
Type of change
[✔] Bug fix (non-breaking change which fixes an issue)
[✔] New feature (non-breaking change which adds functionality)
[✘] Code style update (formatting, local variables)
[✘] Breaking change (fix or feature that would cause existing functionality to not work as expected)
[✘] This change requires a documentation update
Checklist
[✔] My code follows the code style of this project.
[✔] I have followed the contribution guidelines
[✔] I have performed a self-review of my own code.
[✔] I have ensured my changes don't generate …

feat : changed the review page completely to enhance UI and UX

---

login.html

Enhanced Login Page UI by Updating Font Color for Better User Experience
#1054
-->

[PERF] Enhanced Login Page UI by Updating Font Color for Better User Experience

---

tooltips.html

https://github.com/user-attachments/assets/6fa120b8-ed02-4964-a287-7e47a5a60b2e
This is the sample of the feature implemented
This pull request implements an enhanced tooltip feature for the Canvas Editor controls to improve user experience and accessibility. Tooltips provide brief descriptions of each control, helping users understand the functionality of tools before interacting with them.
Key Changes:
Tooltips Added: Each control (Brush, Eraser, Color Picker, Shape Selector, Undo, Redo, Clear Canvas) now displays a tooltip with a brief description on hover.
Enhanced Visuals: Buttons have been styled with vibrant colors, hover effects, and box shadows to enhance visual appeal and interactivity.
Buttons scale up slightly and change to a darker shade on hover, providing clear feedback to …

Enhance Canvas Editor with Interactive Tooltips

---

index.html

Closes: #951 
As it can be seen in issue, the home page was not well designed and had many duplicate content. Now the current home page looks good with properly placed navbar, properly aligned tools for designing, subscribe to newletter must enter a valid email, social icons added .
By running in live server
Before: can be seen in issue
After:

home page redesign

---

index.html

Hello, PR
Add new feature - #1014
Add a pop up dialog box for Polls/Survey done properly -
https://github.com/user-attachments/assets/04001213-be6d-4afa-a037-060b7c92395f

Add a pop up dialog box for Polls/Survey done ! #1014 🌟🌟🌟

---

login.html
signup.html

#1045  Enhancement of SignUp Page : revamp the Signup Page for Improved User Experience

---

Blog_page.html
Faq.html
Feedback.html
about-us.html
about.html
blog.html
contributors.html
index.html
login.html
privacy.html
review.html
signup.html
tooltips.html
tutorial.html

https://github.com/user-attachments/assets/8d6bfc5b-9321-4593-a005-6642105372e8

Enabled Custom cursor effect

---

.github/ISSUE_TEMPLATE/feature-request.yml
README.md
repo_structure.txt

Closes: #1060 
I add a feature request

Add a feature request

---

Blog_page.html

Fixes #1057
add hover effects in blog page
https://github.com/user-attachments/assets/b865b59c-aa13-46d5-b897-8cdc4504842a
plz review it @vishanurag 
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] Code style update (formatting, local variables)
- [x ] I have followed the contribution guidelines
- [x ] I have performed a self-review of my own code.
- [x ] I have resolved all merge conflicts.

Fix issue #1507 add hover effects in blog page to media icons

---

testimonial.html

Title of the Pull Request
[✔] Have you renamed the PR Title in a meaningful way?
Description
This pull request implements UI enhancements for the testimonial page to improve user experience and interactivity while maintaining the existing structure. Key changes include:
-Updated layout for better alignment and spacing of testimonial items.
-Introduced a visually appealing dark theme with colorful elements.
-Improved overall responsiveness and aesthetics to engage users more effectively.
These changes aim to create a more engaging and visually appealing experience for users, encouraging interaction with the testimonials.
Type of change
[✔] Bug fix (non-breaking change which fixes an issue)
[✔] New feature (non-breaking change which adds functionality) …

feat : Updated whole testimonial page to enhance UI and UX

---

README.md

**Title:** docs: Enhance and Structure the Contributor Section
Closes: #1036 
This PR enhances the Contributor section in the README for better organization and visual appeal. The contributor visuals now utilize the Vaunt API for a dynamic, up-to-date display, making it easier for new contributors to feel acknowledged. Added structured alignment for contributor images to improve readability and responsiveness.
Key Changes:
- Updated the contributor graph to dynamically fetch and display contributors with the Vaunt API.
- Structured the contributor section to enhance readability.
- Made contributor images responsive for better alignment on different screen sizes.
The updated contributor section was tested by:
1. Viewing the README on different screen sizes to confirm the responsiveness of …

Enhance and Structure the Contributor Section

---

README.md

**PR Title**: Enhanced Footer with Social Links
---
Closes: #1037 
This pull request adds an enhanced footer to the README file, including social media links for improved visibility and easy connection with contributors and users. The added footer allows visitors to quickly connect with the project team or follow updates, increasing engagement and accessibility.
---
The changes were tested as follows:
- **Visual Check**: The footer and social links were verified in a Markdown preview tool to ensure correct alignment, functionality, and design consistency.
- **Link Verification**: Each link was tested to confirm they redirect to the appropriate social media profiles or contact options.
- **Responsive Check**: The footer layout was tested for responsiveness across different screen sizes to …

Enhanced Footer with Social Links

---

review.html

Fixes #1050
Separate Review Page and Draw Section for Improved Clarity
Closes: #1065

Separate Review Page and Draw Section for Improved Clarity

---

Feedback.html

@somyadipghosh @vishanurag please review and merge it

added back to home button in Feedback page

---

index.html

Done with the changes. Please merge it @vishanurag

Added confirmation dialog for "Clear" button

---

.github/workflows/auto-comment-issue.yml
.github/workflows/auto-label.yml

-  **for Issues Auto-comment**
- **Implement Auto-Labeling Workflow for GitHub**
Closes:r #1042 #1041

Implement a Github Workflow

---

blog.html

Fixes #<issue-number>1048
Closes: #1048 <issue number>
The PR description should include 'Fixes #1048' if addressing an issue.
Process completed with exit code 1.
before
after

#1048  Enhance Design of Latest Blog Post Page and Footer

---

review.html

Closes: #931 
Initially there was no logo in the review page. I have added the logo and and also made sure that it redirects to home page when clicked.

fix: added-logo-to-page-and-made-sure-it-redirects-to-home-page

---

Faq.html
about-us.html
community.html
index.html
privacy.html
testimonial.html

🧑‍💻: Dynamic copyright section #1076 
Closes: #1076 
automated the copyright section 
yes i have tested locally.

 🧑‍💻: Dynamic copyright section #1076 

---

canva.css
canva.html
canva.js
canva.md

I have implemented the features as mentioned above along with few changes in the layout the the website

Implementing function bold ,italic .

---

testimonial.html

#1004 Text Not Visible on Testimonial Page and Suggestion for Images
The PR description should include 'Fixes #1004 ' if addressing an issue.
Process completed with exit code 1.
refactor:   i have made some changes in code to improvise it.
Fixes #<issue-number>1004
Closes: #1004 
The PR description should include 'Fixes https://github.com/vishanurag/Canvas-Editor/issues/1004' if addressing an issue.
Process completed with exit code 1.

#1004 Text Not Visible on Testimonial Page & Suggestion for Images.

---

Blog_page.html
about-us.html
auth.css
auth.html
contributors.html
index.html
privacy.html
review.html
testimonial.html

Closes: #1093 
Changed the style of the Sign in and sign out page
When there is a issue , i open the inspect option in web browser and see where the problem is happening.

Sign in and sign out page enhancement

---

README.md
canva.js
repo_structure.txt

**1.Object-Oriented Reorganisation:**
* transformed the procedural code into a DrawingApp class-based framework.
* Using a state object for centralised state management
* Better encapsulation and organisation of the method
**2. Enhancements to Readability and Performance:**
* For a more succinct radius computation, Math.hypot() was used rather of Math.sqrt(Math.pow()).
* To prevent duplicate documents, DOM element references were cached at the top.calls to querySelector/getElementById
* Object destructuring was employed to minimise repetitive property access and streamline event handling.
**3. Organising Events:**
* One-bind centralised event bindingThe Events() function
* To keep event handlers in the proper context, use.bind(this).
* made a distinct …

refactor: Optimizing State Management and Event Handling for Canvas Drawing Application

---

index.html

Improves overall UI of home page 

---

index.html

Color of Canvas Editor and font style,size has been changed
Closes: #1135

Changed the appearance of h1 under Navbar

---

auth.html

Closes: #1134 
Dash eye Icon Script added in sign in and sign up page
https://github.com/user-attachments/assets/bb7af121-921b-4106-a838-f258822241d1

Dash eye Icon Script added

---

index.html
tutorial.html

Closes: #1107 
I have made changes in the website according to a theme that was there. I think according to the canvas website that gradient design really suits well.
I have done changes in tutorial.html you can check.
https://github.com/user-attachments/assets/097bf7a9-1875-41eb-bfea-3b95c2bbabef

 feat: Redesign the tutorial page according to the theme.Issue(#1107) 

---

Feedback.html

@vishanurag @somyadipghosh please review and merge it
before
after

Fixed Feedback Forum

---

auth.html

auth.html code added

---

README.md

this pull request is the extension of the issue #1021 
where I added the contact.css and contact.html to the current project structure and erased the previous not functioning CSS file. 
Please review it too

 README.md Update for contact form 

---

testimonial.html

Closes: #771 
Fixes #771 
This PR  with newly designed testinomial page makes this website more visually appealing
https://github.com/user-attachments/assets/0e611f44-f3d2-405b-8294-03037f4d0931

feat: Redesigning of the testimonial page(#771)

---

Blog_page.html
Faq.html
about-us.html
about.html
blog.html
contributors.html
privacy.html
review.html
testimonial.html
tutorial.html

Enhanced scroll back button to all the pages  with a progress ring.
Closes: #1149 
https://github.com/user-attachments/assets/3c61270e-af20-46cf-aab3-94824364f50e
-->

feat: Enhanced scroll back button to all the pages with a progress ring.

---

index.html
profile.html
testp.css
testp.js

Hello, PR
Add new feature - #1143
Add a normal user profile page and a profile icon in the home page that redirects to the profile page done -
https://github.com/user-attachments/assets/60d75c99-afa0-45b4-b7d3-276824713368

Add a User Profiles page done ! #1143

---

Faq.html

Closes: #1168 
I have added the faq page according to the theme of the website.
using go live i have made sure the changes are made properly.
https://github.com/user-attachments/assets/da2b1766-d74c-41aa-bd14-fa21194f66f4

feat: Redesign the faq page according to the theme. (Issue#1168)

---

README.md
repo_structure.txt
testimonial.html
tutorial.html

@vishanurag @somyadipghosh please review and merge it in level 3
before
https://github.com/user-attachments/assets/1c7cf34d-5e92-4c51-8b46-0acddae6f18e
after
https://github.com/user-attachments/assets/ced3be9f-09d2-446c-b5b4-93d89a88f604

Fixed whole tutorial page

---

README.md
repo_structure.txt
testimonial.html

@somyadipghosh @vishanurag please review and merge it in higher level
before
after
https://github.com/user-attachments/assets/eb5f06c2-e47f-49bd-bae5-fc2db536c501

Fixed whole testimonial page 

---

contact.html
index.html

Enhancing the CSS styling of the contact us form✨
Closes: #1174 
Enhancing the CSS styling of the contact us form

Enhancing the CSS styling of the contact us form✨

---

contributors.html
style.css

Add Project Statistics in Contributors page done - #1203

Add Project Statistics in Contributors page done ! #1203

---

Faq.html

Closes: #1221
When one question is opened, the previously opened question closes and also closes when clicking outside of any question.
Click a question, then click another question.
https://github.com/user-attachments/assets/65a53490-31ac-4e84-9294-9b32a04b054b
<!--

💥FIX : FAQ Auto close issue

---

index.html

This PR introduces a fresh, vibrant look to the Canvas Editor interface with new icons. These enhancements aim to improve user interaction, making the tool more visually appealing and easier to use.
This PR introduces a fresh, vibrant look to the Canvas Editor interface with new icons, and updated color. These enhancements aim to improve user interaction, making the tool more visually appealing and easier to use.
Replaced standard buttons with modern icons for key tools
Icons and Tooltips: Hover over each tool to see its name and confirm its function.
Before
After

Revamped Canvas Editor Interface with Vibrant Icons

---

Feedback.html

Closes: #1236 
The mouse animation error is fixed on the feedback page.
Go to feedback page and test the animation.

🛠️FIX : Mouse animation error on  feedback page

---

Faq.html

###Added Scrollup button 
- [X ] Have you renamed the PR Title in a meaningful way?
Closes: #1228 
Added the scrollup button in faqpage similar to those existing in other pages
- [X ] New feature (non-breaking change which adds functionality)
- [ X] Code style update (formatting, local variables)
- [X ] My code follows the code style of this project.
- [ X] I have followed the contribution guidelines
- [ X] I have performed a self-review of my own code.
- [ X] I have ensured my changes don't generate any new warnings or errors.
- [ X] I have resolved all merge conflicts.

feat:Added scrollup button in FAQpage

---

.github/Issue_templates/backend_issue.yml

Closes: #1230 
This PR adds a new Backend Issue Report Template to help contributors report backend-related issues effectively. The template includes fields for the error message, environment details, and steps to reproduce, enabling maintainers to identify and troubleshoot backend issues quickly.
- Created a structured Backend Issue Report Template with fields for error logs, environment details, and reproduction steps.
- Updated the documentation with instructions for using the Backend Issue Report Template.
- Ensured the template is easy to understand and comprehensive for both contributors and maintainers.
The template was tested by creating several mock backend issue reports using the new format. Feedback was gathered from team members to ensure all necessary information is captured. …

ADD Backend Issue Report Template

---

about-us.html

Closes: #1240 
Missing mouse animation animation added and some more errors fixed.
https://github.com/user-attachments/assets/ebe0d2dc-d9ce-427c-9ab7-b460f05b2c3b

🛠️FIX : Mouse animation and many more 

---

Faq.html
about-us.html
privacy.html
testimonial.html
tutorial.html

- [X ] Have you renamed the PR Title in a meaningful way?
Closes: #1229 
Added footer components to the different pages of the website
- [ X] New feature (non-breaking change which adds functionality)
- [ X] Code style update (formatting, local variables)
- [ X] My code follows the code style of this project.
- [ X] I have followed the contribution guidelines
- [ X] I have performed a self-review of my own code.
- [ X] I have ensured my changes don't generate any new warnings or errors.
- [ X] I have resolved all merge conflicts.

feat:Added footer section to different pages

---

about-us.html

Closes: #1244 
About Us page broken image fixed.
Go to About us page and check the image .

🛠️FIX : Broken image on About Us page 

---

index.html
profile.html
profileedit.html
testp.js

Add Edit Profile Feature in Profile Page done - #1214 
https://github.com/user-attachments/assets/9b1aa31f-e44e-4d8d-b129-abe7c6b48dab

Add Edit Profile Feature in Profile Page done ! #1214 🟢🟢🟢 

---

tutorial.html

Closes: #1248 
Missing Mouse animation added on Tutorial page.
Go to Tutorial page and check.

💥FIX :  Missing Mouse animation on Tutorial page

---

community.html

Modified community.html file 
Closes: #1209 
i have changed  community.html file in order to give page a better design , with color themes different than previous one , ,recreated navbar , added hover effects .
##Checklists
##Screenshots

Modified community.html page

---

Blog_page.html

Closes: #1250 
Broken images on the Blog page and Back to the Top button fixed.

💥FIX : Broken images on Blog page and Back to Top button 

---

index.html

Remove duplicate login/sign up page button done - #1269
Before -
Now -
-->

Remove duplicate login/sign up page button done 🐞🐞🐞 ! #1269

---

privacy.html

1. Fixed overflow issues
2. updated media queries

refactored privacy.html and removed overflow, added navbar toggler

---

README.md

🔄 Pull Request: Add MIT License Section to README
📌 Issue Reference
Closes #1316
👤 Contributor
GitHub Username: [@vinitjain2005](https://github.com/vinitjain2005)
Branch Name: add-license-section-readme
Commit Message: 📄 Added MIT License section to README
📝 Summary
This PR adds a properly formatted MIT License section to the bottom of the README.md file, including:
📎 A clickable badge showing the license type.
📃 A brief description of the license.
🔗 A direct link to the LICENSE file for easy access.
✨ Changes Made
✅ Updated README.md to include a new section titled License
✅ Included a MIT license badge from [Shields.io](https://shields.io/)
✅ Aligned the license text with the rest of the README's styling
✅ Linked the section to the actual LICENSE file
📁 Files Modified
README.md
✅ …

📄 Added MIT License section to README

---

privacy.html

Closes: #<#1326>
I have changes the format of heading in privacy section also improve the code readability.
I have tested it in my local machine.

style: in privacy section need to improve. #1326

---

Faq.html
index.html

This pull request fixes a layout issue where the **"Visitor"** count box visually overlapped with the chat icon.  
The overlap caused the UI to appear cluttered and reduced readability.  
The update ensures proper spacing between the visitor counter and the chat icon, improving both aesthetics and usability.
Fixes #1336

Resolve overlap between visitor counter and chat icon

---

Blog_page.html
Faq.html
about-us.html
blog.html
index.html
privacy.html
review.html
src/Scripts/typing.js
src/Styles/typing.css
testimonial.html
tutorial.html

- [✔️] Have you renamed the PR Title in a meaningful way?  
- 
Closes: #1344 after merging the PR
1-> I have Make footer enhance 
2->Added typing animation on all the webpages of nav-links -> whenever you landed on page or scroll it will restart
https://github.com/user-attachments/assets/2c665385-0d9c-4b81-9ab0-eb8522dc40c8
1-> I have tested using console dev tools and vs code editor
1->I had change the footer section and added new typing css and js file so that they can fit to all navlinks  
- [✔️] New feature (non-breaking change which adds functionality)
- [✔️] Code style update (formatting, local variables)  
- [✔️] My code follows the code style of this project.
- [✔️] I have followed the contribution guidelines
- [✔️] I have performed a self-review of my own code.
- [✔️] I have …

SOlved issue #1344 footer Ui enhance and typing animation added in all Nav links

---

index.html

This PR addresses Issue #1348 and improves the overall Home Page UI/UX.
Updated the Home Page theme to match other pages (replaced inconsistent pink with the standard black theme).
Enhanced UI layout for a cleaner and more professional look.
Added professional action buttons (e.g., brushes, save, download, Canva-style actions).
Ensured a consistent design language across the application.
These changes make the Home Page visually appealing, user-friendly, and consistent with the rest of the application.
[Old Home Page]
[New Home Page]

feat: improved Home Page frontend UI and styling for better appearance

---

index.html

Closes: #1355 
- This PR updates the Visitor button styling to align with the application’s pink/purple theme.
- Replaced the semi-transparent white background with a solid theme color.
- Updated text color to white for better contrast.
- Adjusted hover shadow to use a purple accent.
- Improved consistency in both light and dark mode.
-  Code style update (UI styling, no functional change)
- My code follows the code style of this project.
- I have followed the contribution guidelines.

style: update Visitor button color to match theme

---

Feedback.html

Fixes #1333
- Added validation for the feedback form.
- Prevents submission when rating is not provided.
- Shows an error message without turning the stars red.
- Tested by submitting the form without rating → error message displayed correctly
- Tested by filling rating → form submitted successfully

Fix #1333: added validation for feedback form
